### PR TITLE
Release 7.0.0

### PR DESCRIPTION
**Pull request by traylenator**
Release 7.0.0

### CODE REVIEW

**Comment by traylenator** [comment]
Think #445 is only close one.

**Comment by traylenator** [comment]
> #433 and #432 are duplicate in the changelog
Removed one of the enhancement tags  which is is I presume the correct thing to do.

**Comment by TheMeier** [comment]
Hm I guess you also need the skip label on the issue #432

**Comment by bastelfreak** [comment]
the systemd module is a dependency to many others. Does it make sense to already drop EL7 support as well? That will save us one breaking change that'e due in a few weeks.

**Comment by bastelfreak** [comment]
And Debian 10 is really already dead, so please let us include https://github.com/voxpupuli/puppet-systemd/pull/448

**Review by ekohl — CHANGES_REQUESTED** [review]
I think https://github.com/voxpupuli/puppet-systemd/pull/449 should be merged before we release this.

**Comment by TheMeier** [comment]
#449 is merged, but changelog needs to be re-generated

**Comment by traylenator** [comment]
Obsoleted by #456

**Pull request closed without merging**
