### PR TITLE
Add support for Ubuntu 22.04

### PR DESCRIPTION
**Pull request by simondeziel**
Drop a few OS releases that are EOL and add some fresh Fedora ones.

### CODE REVIEW

**Review by ekohl — APPROVED** [review]

**Comment by simondeziel** [comment]
I just updated the PR to drop the now unused `data/Debian-8.yaml` and `data/Ubuntu-16.04.yaml` files.

**Review by kenyon — APPROVED** [review]

**Comment by saz** [comment]
What about adding Ubuntu 22.04 as supported?

**Review by smortex — APPROVED** [review]

**Comment by jhoblitt** [comment]
I prefer that dropping of OS support is done in an individual PR so that it appears clearly in the generated changelog.

**Comment by ekohl** [comment]
I agree with @jhoblitt so I've merged his PRs. Can you rebase this?

**Comment by jhoblitt** [comment]
Most of the OS support changes were implemented as:

- #305 
- #307 
- #308 
- #310

**Comment by simondeziel** [comment]
@ekohl @jhoblitt done.

**Review by jhoblitt — APPROVED** [review]
LGTM as ubuntu 22.04 support. Will merge when gha passes.

**Pull request merged**
