### PR TITLE
Correct typing for IOReadIOPSMax, IOWriteIOPSMax,... in systemd::manage_dropin

### LINKED ISSUE #424: IODeviceWeight, IOReadIOPSMax, .. do not work in systemd::manage_unit or systemd::dropin_file
The current types for these parameters for service and slice:

```
Optional['IODeviceWeight']      => Array[Hash[Stdlib::Absolutepath, Integer[1,10000], 1, 1]],
Optional['IOReadBandwidthMax']  => Array[Hash[Stdlib::Absolutepath, Pattern['^(\d+(K|M|G|T)?)$'], 1, 1]],
Optional['IOWriteBandwidthMax'] => Array[Hash[Stdlib::Absolutepath, Pattern['^(\d+(K|M|G|T)?)$'], 1, 1]],
Optional['IOReadIOPSMax']       => Array[Hash[Stdlib::Absolutepath, Pattern['^(\d+(K|M|G|T)?)$'], 1, 1]],
Optional['IOWriteIOPSMax']      => Array[Hash[Stdlib::Absolutepath, Pattern['^(\d+(K|M|G|T)?)$'], 1, 1]],
```

Are incompatible with the template - `templates/unit_file.epp`.

This error was introduced in v6.0.0 with #367

### PR DESCRIPTION
**Pull request by traylenator**
#### Pull Request (PR) description

Using any of the following directives in `systemd::manage_dropin` or `systemd::manage_unit` resulted in a compilation error.

* `IODeviceWeight`
* `IOReadBandwidthMax`
* `IOWriteBandwidthMax`
* `IOReadIOPSMax`
* `IOWriteIOPSMax`

The types for these directives in `Systemd::Unit::Slice` and `Systemd::Unit::Service` have now been updated.

Example usage:

```puppet
systemd::manage_dropin { 'devicelimits.conf':
  unit          =>  'special.service',
  service_entry => {
   'IOReadIOPSMax' => [
     ['/dev/afs',100],
     ['/dev/gluster','1000K'],
   ],
  },
}
```

would result in a drop in file of:

```config
[Service]
IOReadIOPSMax=/dev/afs 100
IOReadIOPSMax=/dev/gluster 1000K
```

#### This Pull Request (PR) fixes the following issues
* Fixes #424 

#### Worth Noting
* The Types here are different to what the existing `systemd::service_limit` uses for these parameters.
* My aim following this is to make `systemd::service_limits` a wrapper to `systemd::manage_dropin`. 
  it contains a translation for these parameters to maintain backwards compatibility.
* `systemd::service_limits` could then be deprecated.

### CODE REVIEW

**Comment by traylenator** [comment]
Very open to the simpler:

```puppet
systemd::manage_dropin { 'devicelimits.conf':
  unit          =>  'special.service',
  service_entry => {
   'IOReadIOPSMax' => [
      '/dev/afs 100',
      '/dev/gluster  1000K',
   ],
  },
}
````
:+1:  or :-1: for this simpler one.

**Comment by traylenator** [comment]
Tests should be fixed by #431

**Review by bastelfreak — APPROVED** [review]

**Comment by TheMeier** [comment]
Maybe make a type for 
```
Variant[Tuple[Stdlib::Absolutepath, Systemd::Unit::Amount],Array[Tuple[Stdlib::Absolutepath, Systemd::Unit::Amount]]]
```
Systemd::Unit::Bandwidth?

**Comment by traylenator** [comment]
> Maybe make a type for 
> ```
> Variant[Tuple[Stdlib::Absolutepath, Systemd::Unit::Amount],Array[Tuple[Stdlib::Absolutepath, Systemd::Unit::Amount]]]
> ```
> and
> ```
> Array[Tuple[Stdlib::Absolutepath, Systemd::Unit::Amount]]
> ```
> Systemd::Unit::Bandwidth?

I don't this is used anywhere else.
I certainly don't want to move away from the obvious to read.
```
variant[array[thing],thing]
```

So would only leave the tuple to simplify and that's simple already. :-)

**Review by TheMeier — APPROVED** [review]

**Pull request merged**
