### PR TITLE
release 4.0.0

### LINKED ISSUE #298: New release
would be nice to have a new release to pick up systemd::manage_unit and systemd::manage_dropin

### PR DESCRIPTION
**Pull request by jhoblitt**
Resolves #298

### CODE REVIEW

**Comment by jhoblitt** [comment]
@saz Is #294 correctly labeled as a bug?  The PR which resolved, #296, it is marked as an enhancement.

**Comment by saz** [comment]
As the package is required to get timesyncd working, I'd say yes.

**Comment by jhoblitt** [comment]
@saz Does that mean #296 should be labeled as a bug fix?

**Comment by saz** [comment]
Yes. I don't see it as an enhancement

**Review by simondeziel — APPROVED** [review]

**Review by ekohl — CHANGES_REQUESTED** [review]
I merged https://github.com/voxpupuli/puppet-systemd/pull/313 and marked it as bug, but that was under the assumption it was already released. Now that it's merged prior to the release, any idea how we should reflect this?

At least make sure we deal with this before we really release.

**Comment by jhoblitt** [comment]
@ekohl I don't see why we can't change the label on #313 and regenerate the changelog. I'll do that now...

**Comment by jhoblitt** [comment]
Changelog has been regenerated after the merge of #313, the closure of additional issues, and PR label changes.

**Pull request merged**
