### PR TITLE
modulesync 7.0.0

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Review by evgeni — APPROVED** [review]

**Comment by ekohl** [comment]
Oracle failures are probably related. Previously we didn't test that at all.

**Comment by evgeni** [comment]
> Oracle failures are probably related. Previously we didn't test that at all.

Nah, they failed in my #375 too, same error

**Comment by ekohl** [comment]
Ah yes, https://github.com/voxpupuli/puppet_metadata/commit/7dd3f64c8fde225aa04210edead52c8c75c9795c was a minor release.

**Comment by ekohl** [comment]
I'm going to blame Oracle on this: Why is it even attempting to install `.i686`?
```
   Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install systemd-resolved' returned 1: Error: Package: systemd-resolved-219-78.0.1.el7_9.2.i686 (ol7_latest)
             Requires: systemd = 219-78.0.1.el7_9.2
             Installed: systemd-219-78.0.10.el7_9.7.x86_64 (@ol7_latest/$releasever)
                 systemd = 219-78.0.10.el7_9.7
             Available: systemd-219-57.0.1.el7.x86_64 (ol7_latest)
                 systemd = 219-57.0.1.el7
             Available: systemd-219-57.0.1.el7_5.1.x86_64 (ol7_latest)
                 systemd = 219-57.0.1.el7_5.1
             Available: systemd-219-57.0.1.el7_5.3.x86_64 (ol7_latest)
                 systemd = 219-57.0.1.el7_5.3
             Available: systemd-219-62.0.1.el7.x86_64 (ol7_latest)
                 systemd = 219-62.0.1.el7
             Available: systemd-219-62.0.3.el7.x86_64 (ol7_latest)
                 systemd = 219-62.0.3.el7
             Available: systemd-219-62.0.4.el7_6.2.x86_64 (ol7_latest)
                 systemd = 219-62.0.4.el7_6.2
             Available: systemd-219-62.0.4.el7_6.3.x86_64 (ol7_latest)
                 systemd = 219-62.0.4.el7_6.3
             Available: systemd-219-62.0.4.el7_6.5.x86_64 (ol7_latest)
                 systemd = 219-62.0.4.el7_6.5
             Available: systemd-219-62.0.4.el7_6.6.x86_64 (ol7_latest)
                 systemd = 219-62.0.4.el7_6.6
             Available: systemd-219-62.0.4.el7_6.7.x86_64 (ol7_latest)
                 systemd = 219-62.0.4.el7_6.7
             Available: systemd-219-62.0.4.el7_6.9.x86_64 (ol7_latest)
                 systemd = 219-62.0.4.el7_6.9
             Available: systemd-219-67.el7_7.1.x86_64 (ol7_latest)
                 systemd = 219-67.el7_7.1
             Available: systemd-219-67.0.1.el7.x86_64 (ol7_latest)
                 systemd = 219-67.0.1.el7
             Available: systemd-219-67.0.1.el7_7.2.x86_64 (ol7_latest)
                 systemd = 219-67.0.1.el7_7.2
             Available: systemd-219-67.0.5.el7_7.2.x86_64 (ol7_latest)
                 systemd = 219-67.0.5.el7_7.2
             Available: systemd-219-67.0.5.el7_7.3.x86_64 (ol7_latest)
                 systemd = 219-67.0.5.el7_7.3
             Available: systemd-219-67.0.5.el7_7.4.x86_64 (ol7_latest)
                 systemd = 219-67.0.5.el7_7.4
             Available: systemd-219-67.0.7.el7_7.4.x86_64 (ol7_latest)
                 systemd = 219-67.0.7.el7_7.4
             Available: systemd-219-73.0.1.el7.1.x86_64 (ol7_latest)
                 systemd = 219-73.0.1.el7.1
             Available: systemd-219-73.0.1.el7_8.5.x86_64 (ol7_latest)
                 systemd = 219-73.0.1.el7_8.5
             Available: systemd-219-73.0.1.el7_8.6.x86_64 (ol7_latest)
                 systemd = 219-73.0.1.el7_8.6
             Available: systemd-219-73.0.1.el7_8.7.x86_64 (ol7_latest)
                 systemd = 219-73.0.1.el7_8.7
             Available: systemd-219-73.0.1.el7_8.8.x86_64 (ol7_latest)
                 systemd = 219-73.0.1.el7_8.8
             Available: systemd-219-73.0.1.el7_8.9.x86_64 (ol7_latest)
                 systemd = 219-73.0.1.el7_8.9
             Available: systemd-219-73.0.3.el7_8.9.x86_64 (ol7_latest)
                 systemd = 219-73.0.3.el7_8.9
             Available: systemd-219-78.0.1.el7.x86_64 (ol7_latest)
                 systemd = 219-78.0.1.el7
             Available: systemd-219-78.0.1.el7.1.x86_64 (ol7_latest)
                 systemd = 219-78.0.1.el7.1
             Available: systemd-219-78.0.1.el7_9.2.x86_64 (ol7_latest)
                 systemd = 219-78.0.1.el7_9.2
             Available: systemd-219-78.0.1.el7_9.3.x86_64 (ol7_latest)
                 systemd = 219-78.0.1.el7_9.3
             Available: systemd-219-78.0.3.el7_9.3.x86_64 (ol7_latest)
                 systemd = 219-78.0.3.el7_9.3
             Available: systemd-219-78.0.5.el7_9.3.x86_64 (ol7_latest)
                 systemd = 219-78.0.5.el7_9.3
             Available: systemd-219-78.0.7.el7_9.3.x86_64 (ol7_latest)
                 systemd = 219-78.0.7.el7_9.3
             Available: systemd-219-78.0.7.el7_9.5.x86_64 (ol7_latest)
                 systemd = 219-78.0.7.el7_9.5
             Available: systemd-219-78.0.9.el7_9.5.x86_64 (ol7_latest)
                 systemd = 219-78.0.9.el7_9.5
             Available: systemd-219-78.0.9.el7_9.7.x86_64 (ol7_latest)
                 systemd = 219-78.0.9.el7_9.7
```

**Pull request merged**
